### ISSUE TITLE
Fix me 

### ISSUE THREAD

**Issue by FightingForFun** [NourEddineX/AutoArpSpoof#1]
Good afternoon.
I install and download your auto bash script... and found some mistakes.

1. Add ip_forward check. (Need to be 1).
2. Add slow network scan for wireless clients.

(at you now, arpspoof -i wlan0 -t gatewayip targetip. Need to be...)
3. arpspoof -i wlan0 -t gatewayip targetip and at same time arpspoof -i wlan0 -t targetip gatewayip.

4. More information about work aprspoof's commands. Because i'm not see this.

Thx. Sorry for my bad english :))

**Comment by NourEddineX** [comment]
## 1
We don't want to make "echo 1 > /proc/sys/net/ipv4/ip_forward" .. some people need such script for cutting off network for other clients.. not for sniffing their traffic
## 2
I'll try replace the scanning method with another method supporting slower networks
## 3
I don't know how I missed that ! thank you for submitting this issue :+1: 
## 4
I think if someone don't know what's arpspoof .. he won't need to use such script :smiley_cat: 
but I'll try to provide some Documentation links
#########
Never mind.. my english is bad too :sweat_smile:
